// CLIPathInstaller.swift
// Manages installation of the CLI tool to the user's PATH by creating
// symlinks in /usr/local/bin.
//
// - Debug builds install as: rpce-cli-debug
// - Release builds install as: rpce-cli
//
// This allows users to invoke the CLI directly from their terminal.

#if !os(Linux)
    import Foundation
    import OSLog

    enum CLIPathInstaller {
        private static let logger = Logger(subsystem: "CLI.PathInstaller", category: "install")

        /// The name of the CLI command in PATH (nonisolated - compile-time constant)
        nonisolated static var cliCommandName: String {
            #if DEBUG
                return "rpce-cli-debug"
            #else
                return "rpce-cli"
            #endif
        }

        /// The name of the claude-rp wrapper command (nonisolated - compile-time constant)
        nonisolated static var claudeRPCommandName: String {
            #if DEBUG
                return "claude-rpce-debug"
            #else
                return "claude-rpce"
            #endif
        }

        /// The installation directory for the CLI symlink (nonisolated - constant)
        nonisolated static let installDirectory = "/usr/local/bin"

        /// Full path where the CLI symlink will be created (nonisolated - derived from constants)
        nonisolated static var installPath: String {
            "\(installDirectory)/\(cliCommandName)"
        }

        /// Full path where the claude-rp wrapper will be created
        nonisolated static var claudeRPInstallPath: String {
            "\(installDirectory)/\(claudeRPCommandName)"
        }

        /// Returns the path to the bundled CLI executable
        @MainActor
        static var bundledCLIPath: String? {
            Bundle.main.url(forAuxiliaryExecutable: "repoprompt-mcp")?.path
        }

        /// Built-in Claude Code tools to disable in the claude-rp wrapper.
        /// These overlap with RepoPrompt MCP tools and should use RP versions instead.
        private static let claudeRPDisallowedTools = ["Read", "Write", "Edit", "Glob", "Grep"]
        private static let claudeRPManagedMarker = "# claude-rpce: Claude Code wrapper configured for RepoPrompt CE"
        private static let legacyClaudeRPManagedMarkers = [
            "# claude-rp-ce: Claude Code wrapper configured for RepoPrompt CE",
            "# claude-rp: Claude Code wrapper configured for RepoPrompt"
        ]

        private static func isManagedClaudeRPScript(_ content: String) -> Bool {
            content.contains(claudeRPManagedMarker) || legacyClaudeRPManagedMarkers.contains { content.contains($0) }
        }

        /// Path to the MCP config file used by claude-rp wrapper
        private static var claudeRPConfigPath: String {
            let home = FileManager.default.homeDirectoryForCurrentUser.path
            let fileName = MCPConfigExportService.discoveryConfigFileName
            return "\(home)/Library/Application Support/RepoPrompt CE/MCP/\(fileName)"
        }

        /// Generates the shell script content for the claude-rp wrapper
        private static func claudeRPScriptContent() -> String {
            let disallowedToolsArg = claudeRPDisallowedTools.joined(separator: ",")
            let configPath = claudeRPConfigPath
            let environmentExports = MCPIntegrationHelper.claudeProcessEnvironmentOverridePairs
                .map { "export \($0.0)=$" + "{\($0.0):-\($0.1)}" }
                .joined(separator: "\n")
            return """
            #!/bin/bash
            \(claudeRPManagedMarker)
            # Generated by RepoPrompt CE
            #
            # This wrapper runs Claude Code with:
            #   - RepoPrompt MCP server enabled via config file
            #   - Claude MCP timeouts/output limits set in the process environment with user-overridable defaults
            #   - Strict MCP config mode (ignores other MCP configs)
            #   - Built-in file tools disabled (uses RepoPrompt's MCP tools instead)
            #
            # Prerequisites:
            #   1. Claude Code CLI installed (https://docs.anthropic.com/claude-code)
            #   2. RepoPrompt CE app running with MCP server enabled
            #
            # Config file: \(configPath)
            # Disabled tools: \(disallowedToolsArg)

            \(environmentExports)
            exec claude --mcp-config "\(configPath)" --strict-mcp-config --disallowedTools \(disallowedToolsArg) "$@"
            """
        }

        #if DEBUG
            static func test_claudeRPScriptContent() -> String {
                claudeRPScriptContent()
            }

            static func test_isManagedClaudeRPScript(_ content: String) -> Bool {
                isManagedClaudeRPScript(content)
            }
        #endif

        // MARK: - Installation Status

        enum InstallationStatus: Equatable {
            case notInstalled
            case installed
            case installedButStale // Points to wrong location
            case installedByOther // Not our symlink (file exists but not our symlink)
            case directoryMissing // /usr/local/bin doesn't exist
        }

        /// Check the current installation status
        @MainActor
        static func checkStatus() -> InstallationStatus {
            let fm = FileManager.default
            let path = installPath

            // Check if /usr/local/bin exists
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: installDirectory, isDirectory: &isDir), isDir.boolValue else {
                return .directoryMissing
            }

            // Check if file exists at install path
            guard fm.fileExists(atPath: path) else {
                return .notInstalled
            }

            // Check if it's a symlink
            guard let attrs = try? fm.attributesOfItem(atPath: path),
                  let fileType = attrs[.type] as? FileAttributeType,
                  fileType == .typeSymbolicLink
            else {
                // File exists but isn't a symlink
                return .installedByOther
            }

            // Check if symlink points to our CLI
            guard let destination = try? fm.destinationOfSymbolicLink(atPath: path) else {
                return .installedByOther
            }

            guard let bundledPath = bundledCLIPath else {
                return .installedButStale
            }

            if destination == bundledPath {
                return .installed
            } else {
                return .installedButStale
            }
        }

        /// Human-readable description of current status
        @MainActor
        static func statusDescription() -> String {
            switch checkStatus() {
            case .notInstalled:
                "Not installed"
            case .installed:
                "Installed at \(installPath)"
            case .installedButStale:
                "Installed but points to old location"
            case .installedByOther:
                "Path exists but not managed by RepoPrompt"
            case .directoryMissing:
                "\(installDirectory) does not exist"
            }
        }

        // MARK: - Installation

        enum InstallError: LocalizedError {
            case noBundledCLI
            case directoryMissing
            case permissionDenied
            case pathExistsNotOurs
            case scriptFailed(String)
            case unknown(Error)

            var errorDescription: String? {
                switch self {
                case .noBundledCLI:
                    "Could not find the bundled CLI executable"
                case .directoryMissing:
                    "\(installDirectory) does not exist. Create it first with: sudo mkdir -p \(installDirectory)"
                case .permissionDenied:
                    "Permission denied. Administrator access is required."
                case .pathExistsNotOurs:
                    "A file already exists at \(installPath) that wasn't created by RepoPrompt"
                case let .scriptFailed(message):
                    "Installation failed: \(message)"
                case let .unknown(error):
                    "Installation failed: \(error.localizedDescription)"
                }
            }
        }

        /// Install the CLI to PATH using AppleScript for admin privileges
        @MainActor
        static func install() async throws {
            guard let bundledPath = bundledCLIPath else {
                throw InstallError.noBundledCLI
            }

            let status = checkStatus()

            switch status {
            case .directoryMissing:
                throw InstallError.directoryMissing
            case .installedByOther:
                throw InstallError.pathExistsNotOurs
            case .installed:
                logger.info("CLI already installed at \(installPath)")
                return
            case .notInstalled, .installedButStale:
                break
            }

            // Build the shell command to run with admin privileges
            let escapedBundledPath = bundledPath.replacingOccurrences(of: "'", with: "'\\''")
            let escapedInstallPath = installPath.replacingOccurrences(of: "'", with: "'\\''")

            var shellCommand = if status == .installedButStale {
                // Remove old symlink first
                "rm -f '\(escapedInstallPath)' && ln -s '\(escapedBundledPath)' '\(escapedInstallPath)'"
            } else {
                "ln -s '\(escapedBundledPath)' '\(escapedInstallPath)'"
            }

            // Use osascript to request admin privileges
            let script = """
            do shell script "\(shellCommand)" with administrator privileges
            """

            logger.info("Installing CLI: \(shellCommand)")

            do {
                let result = try await runAppleScript(script)
                if let output = result, !output.isEmpty {
                    logger.info("Install output: \(output)")
                }
                logger.info("CLI installed successfully at \(installPath)")
            } catch {
                logger.error("Failed to install CLI: \(error.localizedDescription)")
                if (error as NSError).domain == "com.apple.osascript" {
                    throw InstallError.permissionDenied
                }
                throw InstallError.unknown(error)
            }
        }

        /// Uninstall the CLI from PATH
        @MainActor
        static func uninstall() async throws {
            let status = checkStatus()

            switch status {
            case .notInstalled, .directoryMissing:
                logger.info("CLI not installed, nothing to uninstall")
                return
            case .installedByOther:
                throw InstallError.pathExistsNotOurs
            case .installed, .installedButStale:
                break
            }

            let escapedInstallPath = installPath.replacingOccurrences(of: "'", with: "'\\''")
            let shellCommand = "rm -f '\(escapedInstallPath)'"

            let script = """
            do shell script "\(shellCommand)" with administrator privileges
            """

            logger.info("Uninstalling CLI: \(shellCommand)")

            do {
                let result = try await runAppleScript(script)
                if let output = result, !output.isEmpty {
                    logger.info("Uninstall output: \(output)")
                }
                logger.info("CLI uninstalled successfully")
            } catch {
                logger.error("Failed to uninstall CLI: \(error.localizedDescription)")
                if (error as NSError).domain == "com.apple.osascript" {
                    throw InstallError.permissionDenied
                }
                throw InstallError.unknown(error)
            }
        }

        // MARK: - claude-rp Wrapper Installation

        /// Installation status specific to claude-rp wrapper
        enum ClaudeRPInstallationStatus: Equatable {
            case notInstalled
            case installed
            case installedButOutdated // Script exists but content differs
            case installedByOther // File exists but not our script
            case directoryMissing // /usr/local/bin doesn't exist
        }

        /// Check the claude-rp wrapper installation status
        @MainActor
        static func checkClaudeRPStatus() -> ClaudeRPInstallationStatus {
            let fm = FileManager.default
            let path = claudeRPInstallPath

            // Check if /usr/local/bin exists
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: installDirectory, isDirectory: &isDir), isDir.boolValue else {
                return .directoryMissing
            }

            // Check if file exists at install path
            guard fm.fileExists(atPath: path) else {
                return .notInstalled
            }

            // Read the file contents
            guard let existingContent = try? String(contentsOfFile: path, encoding: .utf8) else {
                return .installedByOther
            }

            // Check if it's our script (current CE marker or a legacy managed marker)
            guard isManagedClaudeRPScript(existingContent) else {
                return .installedByOther
            }

            // Check if content matches current version
            let expectedContent = claudeRPScriptContent()
            if existingContent.trimmingCharacters(in: .whitespacesAndNewlines) ==
                expectedContent.trimmingCharacters(in: .whitespacesAndNewlines)
            {
                return .installed
            } else {
                return .installedButOutdated
            }
        }

        /// Human-readable description of claude-rp status
        @MainActor
        static func claudeRPStatusDescription() -> String {
            switch checkClaudeRPStatus() {
            case .notInstalled:
                "Not installed"
            case .installed:
                "Installed at \(claudeRPInstallPath)"
            case .installedButOutdated:
                "Installed but needs update"
            case .installedByOther:
                "Path exists but not managed by RepoPrompt"
            case .directoryMissing:
                "\(installDirectory) does not exist"
            }
        }

        /// Install the claude-rp wrapper script using AppleScript for admin privileges
        @MainActor
        static func installClaudeRP() async throws {
            let status = checkClaudeRPStatus()

            switch status {
            case .directoryMissing:
                throw InstallError.directoryMissing
            case .installedByOther:
                throw InstallError.pathExistsNotOurs
            case .installed:
                // Wrapper is already installed, but still refresh the MCP config file
                logger.info("claude-rp already installed at \(claudeRPInstallPath)")
                try await MCPConfigExportService.shared.prepareConfigFile()
                logger.info("MCP config file refreshed at \(claudeRPConfigPath)")
                return
            case .notInstalled, .installedButOutdated:
                break
            }

            // Write the script content to a temp file, then move it with admin privileges
            let scriptContent = claudeRPScriptContent()
            let tempDir = FileManager.default.temporaryDirectory
            let tempFile = tempDir.appendingPathComponent("claude-rp-\(UUID().uuidString).sh")

            do {
                try scriptContent.write(to: tempFile, atomically: true, encoding: .utf8)
            } catch {
                throw InstallError.scriptFailed("Failed to write temporary script: \(error.localizedDescription)")
            }

            defer {
                try? FileManager.default.removeItem(at: tempFile)
            }

            let escapedTempPath = tempFile.path.replacingOccurrences(of: "'", with: "'\\''")
            let escapedInstallPath = claudeRPInstallPath.replacingOccurrences(of: "'", with: "'\\''")

            // Move temp file to install location and make executable
            let shellCommand = if status == .installedButOutdated {
                "rm -f '\(escapedInstallPath)' && cp '\(escapedTempPath)' '\(escapedInstallPath)' && chmod +x '\(escapedInstallPath)'"
            } else {
                "cp '\(escapedTempPath)' '\(escapedInstallPath)' && chmod +x '\(escapedInstallPath)'"
            }

            let script = """
            do shell script "\(shellCommand)" with administrator privileges
            """

            logger.info("Installing claude-rp: \(shellCommand)")

            do {
                let result = try await runAppleScript(script)
                if let output = result, !output.isEmpty {
                    logger.info("Install output: \(output)")
                }
                logger.info("claude-rp installed successfully at \(claudeRPInstallPath)")

                // Create the MCP config file that claude-rp references
                try await MCPConfigExportService.shared.prepareConfigFile()
                logger.info("MCP config file created at \(claudeRPConfigPath)")
            } catch {
                logger.error("Failed to install claude-rp: \(error.localizedDescription)")
                if (error as NSError).domain == "com.apple.osascript" {
                    throw InstallError.permissionDenied
                }
                throw InstallError.unknown(error)
            }
        }

        /// Uninstall the claude-rp wrapper from PATH
        @MainActor
        static func uninstallClaudeRP() async throws {
            let status = checkClaudeRPStatus()

            switch status {
            case .notInstalled, .directoryMissing:
                logger.info("claude-rp not installed, nothing to uninstall")
                return
            case .installedByOther:
                throw InstallError.pathExistsNotOurs
            case .installed, .installedButOutdated:
                break
            }

            let escapedInstallPath = claudeRPInstallPath.replacingOccurrences(of: "'", with: "'\\''")
            let shellCommand = "rm -f '\(escapedInstallPath)'"

            let script = """
            do shell script "\(shellCommand)" with administrator privileges
            """

            logger.info("Uninstalling claude-rp: \(shellCommand)")

            do {
                let result = try await runAppleScript(script)
                if let output = result, !output.isEmpty {
                    logger.info("Uninstall output: \(output)")
                }
                logger.info("claude-rp uninstalled successfully")
            } catch {
                logger.error("Failed to uninstall claude-rp: \(error.localizedDescription)")
                if (error as NSError).domain == "com.apple.osascript" {
                    throw InstallError.permissionDenied
                }
                throw InstallError.unknown(error)
            }
        }

        // MARK: - Helper

        private static func runAppleScript(_ script: String) async throws -> String? {
            try await withCheckedThrowingContinuation { continuation in
                DispatchQueue.global(qos: .userInitiated).async {
                    var error: NSDictionary?
                    let appleScript = NSAppleScript(source: script)
                    let result = appleScript?.executeAndReturnError(&error)

                    if let error {
                        let errorMessage = error[NSAppleScript.errorMessage] as? String ?? "Unknown AppleScript error"
                        let nsError = NSError(
                            domain: "com.apple.osascript",
                            code: error[NSAppleScript.errorNumber] as? Int ?? -1,
                            userInfo: [NSLocalizedDescriptionKey: errorMessage]
                        )
                        continuation.resume(throwing: nsError)
                    } else {
                        continuation.resume(returning: result?.stringValue)
                    }
                }
            }
        }
    }
#endif
